### ISSUE TITLE
Whole communications not being pulled from Seattle

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1128]
Seattle has a portal into which they typically enter our requests. The system isn't so bad, because one needn't necessarily sign into the portal to access the communications; they're also emailed to the request page. However, the whole communication isn't always pulled. For example, this communication initially only read: "--- Please respond above this line ---"

https://www.muckrock.com/foi/seattle-69/request-for-sanitized-taser-or-other-body-camera-configuration-data-30304/#comm-313037

I'm adding the rest of communication from the full message in Diagnostics now, but could we ask MuckBot or its minions to please pull in the whole text?

**Comment by morisy** [comment]
I don't know if this is better handled as a bad parsing issue on mailgun's part or through a larger feature adjustment. Beryl, if you could copy in some of the communications that are poorly parsed, that might be helpful. Just links to the "Raw HTML" links from the communications should be good.

**Comment by blipblitz** [comment]
https://www.muckrock.com/foi/seattle-69/90-day-alpr-deletion-script-and-communications-25860/

https://www.muckrock.com/foi/raw_email/278032/

**Comment by blipblitz** [comment]
https://www.muckrock.com/foi/seattle-69/request-for-30-day-alpr-purge-script-and-records-30874/

https://www.muckrock.com/foi/raw_email/314144/

https://www.muckrock.com/foi/raw_email/314662/

https://www.muckrock.com/foi/raw_email/314663/

**Comment by mitchelljkotler** [comment]
This is a failure on mailgun's parsing.  We should probably report it to them.

However, if the emails consistently get cut to just "--- Please respond above this line ---" we can check for that and pull in the whole message despite mailgun's parsing in that case.  Obviously for the long term, less special cases are better, but in the short term less work for Beryl is better.

**Comment by blipblitz** [comment]
Their messages aren't consistently cut off, though it does look like whatever is attached to the raw email is appropriate. In some cases, no email gets through to our front end at all.

**Comment by mitchelljkotler** [comment]
Hmm that might make it a little trickier... is this for all agencies for Seattle?

**Comment by mitchelljkotler** [comment]
Ok, I have implemented a check to see if it looks like the mailgun parser has failed and falls back to including the entire email body if so.  Right now that means if the "stripped" part is blank or is "--- Please respond above this line ---".  Let me know if this is working!  If we need to add more patterns that count as bad we can do that.

**Comment by blipblitz** [comment]
This is still happening. The latest from Phil Mocek, regarding the October 25 communication on this request: https://www.muckrock.com/foi/king-county-73/e-mail-with-neighborhood-safety-alliance-speak-out-seattle-safe-seattle-county-council-42820/ 

I've added the omitted text to the front-facing portion of the communication.

**Comment by mitchelljkotler** [comment]
So based on the history, it looks like this did not cut off the whole communication, but only half of it.  For cases like that there is not much we can do - the algorithm to detect which part of the message we want isn't perfect and unless there are cases we can always detect (it cuts off the entire message, their is always a line like "---Please response above---" we can key off of) there is not much we can do about it besides manually fixing it.  The alternative would be to have all previous replies present in every incoming emailed communication.
